import { theme } from 'antd'

export function createAntdTheme(isDark) {
  return {
    algorithm: isDark ? theme.darkAlgorithm : theme.defaultAlgorithm,
    token: {
      fontFamily: "system-ui, 'Segoe UI', Roboto, sans-serif",
      colorPrimary: "#34d399",
      colorSuccess: "#10b981",
      colorWarning: "#f59e0b",
      colorError: "#ef4444",
      colorInfo: "#34d399",
      colorTextBase: "#1f2937",
      colorBgBase: "#f0fdf4",
      colorPrimaryBg: "#dcfce7",
      colorPrimaryBgHover: "#bbf7d0",
      colorPrimaryBorder: "#86efac",
      colorPrimaryBorderHover: "#4ade80",
      colorPrimaryHover: "#22c55e",
      colorPrimaryActive: "#16a34a",
      colorPrimaryText: "#15803d",
      colorPrimaryTextHover: "#16a34a",
      colorPrimaryTextActive: "#15803d",
      colorSuccessBg: "#d1fae5",
      colorSuccessBgHover: "#a7f3d0",
      colorSuccessBorder: "#6ee7b7",
      colorSuccessBorderHover: "#34d399",
      colorSuccessHover: "#059669",
      colorSuccessActive: "#047857",
      colorSuccessText: "#065f46",
      colorSuccessTextHover: "#047857",
      colorSuccessTextActive: "#064e3b",
      colorWarningBg: "#fef3c7",
      colorWarningBgHover: "#fde68a",
      colorWarningBorder: "#fcd34d",
      colorWarningBorderHover: "#fbbf24",
      colorWarningHover: "#d97706",
      colorWarningActive: "#b45309",
      colorWarningText: "#92400e",
      colorWarningTextHover: "#b45309",
      colorWarningTextActive: "#78350f",
      colorErrorBg: "#fee2e2",
      colorErrorBgHover: "#fecaca",
      colorErrorBorder: "#fca5a5",
      colorErrorBorderHover: "#f87171",
      colorErrorHover: "#dc2626",
      colorErrorActive: "#b91c1c",
      colorErrorText: "#991b1b",
      colorErrorTextHover: "#b91c1c",
      colorErrorTextActive: "#7f1d1d",
      colorInfoBg: "#dcfce7",
      colorInfoBgHover: "#bbf7d0",
      colorInfoBorder: "#86efac",
      colorInfoBorderHover: "#4ade80",
      colorInfoHover: "#22c55e",
      colorInfoActive: "#16a34a",
      colorInfoText: "#15803d",
      colorInfoTextHover: "#16a34a",
      colorInfoTextActive: "#15803d",
      colorText: "#111827",
      colorTextSecondary: "#374151",
      colorTextTertiary: "#6b7280",
      colorTextQuaternary: "#9ca3af",
      colorTextDisabled: "#d1d5db",
      colorBgContainer: "#ffffff",
      colorBgElevated: "#ffffff",
      colorBgLayout: "#f0fdf4",
      colorBgSpotlight: "rgba(34, 197, 94, 0.85)",
      colorBgMask: "rgba(0, 0, 0, 0.45)",
      colorBorder: "#d1d5db",
      colorBorderSecondary: "#e5e7eb",
      borderRadius: 12,
      borderRadiusXS: 3,
      borderRadiusSM: 6,
      borderRadiusLG: 16,
      padding: 16,
      paddingSM: 12,
      paddingLG: 24,
      margin: 16,
      marginSM: 12,
      marginLG: 24,
      boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
      boxShadowSecondary: "0 4px 12px 0 rgba(0, 0, 0, 0.08)"
    },
  }
}
