export const dashboardData = {
  user: {
    name: 'Raka',
    location: 'Jakarta Selatan',
    avatarInitials: 'RA',
  },
  hero: {
    title: 'Barang Layak Pakai, Jangan Sampai Terbuang',
    description:
      'Temukan atau bagikan barang gratis untuk sesama. Bersama kurangi limbah dan bantu komunitas sekitar.',
    primaryAction: 'Upload Barang',
    secondaryAction: 'Jelajahi Barang',
  },
  communityImpact: [
    {
      key: 'shared',
      label: 'Barang Dibagikan',
      value: '1,248',
      icon: 'gift',
      tone: 'green',
    },
    {
      key: 'claimed',
      label: 'Berhasil Diambil',
      value: '856',
      icon: 'hands',
      tone: 'blue',
    },
    {
      key: 'waste',
      label: 'Limbah Dicegah',
      value: '2.4 ton',
      icon: 'leaf',
      tone: 'amber',
    },
  ],
  incomingRequests: [
    {
      id: 'request-1',
      requester: 'Sarah Wijaya',
      avatarInitials: 'SW',
      itemName: 'Rak Buku',
      location: 'Mampang Prapatan',
      message:
        'Sangat butuh untuk menaruh buku-buku kuliah saya yang menumpuk.',
      status: 'new',
    },
    {
      id: 'request-2',
      requester: 'Nabila Putri',
      avatarInitials: 'NP',
      itemName: 'Stroller Bayi',
      location: 'Pancoran',
      message: 'Bisa saya ambil sore ini jika barangnya masih tersedia.',
      status: 'pending',
    },
  ],
  activity: {
    listingsTotal: 4,
    requestTotal: 2,
    statuses: [
      {
        key: 'process',
        label: 'Proses',
        value: 2,
        tone: 'blue',
      },
      {
        key: 'completed',
        label: 'Selesai',
        value: 2,
        tone: 'green',
      },
      {
        key: 'pending',
        label: 'Pending',
        value: 1,
        tone: 'amber',
      },
    ],
    latestRequest: {
      itemName: 'Stroller Bayi',
      status: 'pending',
    },
  },
  categories: [
    {
      key: 'furniture',
      label: 'Furniture',
      icon: 'furniture',
      tone: 'amber',
    },
    {
      key: 'electronics',
      label: 'Elektronik',
      icon: 'electronics',
      tone: 'blue',
    },
    {
      key: 'books',
      label: 'Buku',
      icon: 'books',
      tone: 'green',
    },
    {
      key: 'baby',
      label: 'Bayi & Anak',
      icon: 'baby',
      tone: 'rose',
    },
    {
      key: 'clothes',
      label: 'Pakaian',
      icon: 'clothes',
      tone: 'slate',
    },
    {
      key: 'home',
      label: 'Rumah Tangga',
      icon: 'home',
      tone: 'sky',
    },
  ],
  listings: [
    {
      id: 'item-1',
      title: 'Meja Belajar Kayu',
      category: 'Furniture',
      location: 'Jakarta Selatan',
      timeAgo: '2 jam yang lalu',
      condition: 'Kondisi baik',
      availability: 'tersedia',
      requestStatus: null,
      saved: false,
      visual: 'desk',
    },
    {
      id: 'item-2',
      title: 'Meja Belajar Minimalis',
      category: 'Furniture',
      location: 'Jakarta Selatan',
      timeAgo: '2 jam yang lalu',
      condition: 'Kondisi baik',
      availability: 'tersedia',
      requestStatus: null,
      saved: false,
      visual: 'desk',
    },
    {
      id: 'item-3',
      title: 'Kursi Kantor Ergonomis',
      category: 'Furniture',
      location: 'Tangerang Kota',
      timeAgo: '3 jam yang lalu',
      condition: 'Kondisi baik',
      availability: 'tersedia',
      requestStatus: null,
      saved: true,
      visual: 'chair',
    },
    {
      id: 'item-4',
      title: 'Rak Buku 4 Tingkat',
      category: 'Buku',
      location: 'Jakarta Selatan',
      timeAgo: '5 jam yang lalu',
      condition: 'Terawat',
      availability: 'proses',
      requestStatus: 'process',
      saved: false,
      visual: 'shelf',
    },
    {
      id: 'item-5',
      title: 'Set Peralatan Makan',
      category: 'Rumah Tangga',
      location: 'Depok',
      timeAgo: '6 jam yang lalu',
      condition: 'Lengkap',
      availability: 'pending',
      requestStatus: 'pending',
      saved: false,
      visual: 'tableware',
    },
    {
      id: 'item-6',
      title: 'Bouncer Bayi',
      category: 'Bayi & Anak',
      location: 'Jakarta Selatan',
      timeAgo: '1 hari yang lalu',
      condition: 'Kondisi baik',
      availability: 'selesai',
      requestStatus: 'completed',
      saved: true,
      visual: 'baby',
    },
  ],
}

export const dashboardModules = dashboardData.communityImpact
