export const categoryVisualMap = {
  baby: 'baby',
  books: 'shelf',
  clothes: 'clothes',
  electronics: 'electronics',
  furniture: 'desk',
  home: 'tableware',
}

export const conditionKeys = [
  'good',
  'wellMaintained',
  'complete',
  'needsCleaning',
]

export const dashboardData = {
  user: {
    name: 'Raka',
    location: 'Jakarta Selatan',
    avatarInitials: 'RA',
  },
  communityImpact: [
    {
      key: 'shared',
      value: '1,248',
      icon: 'gift',
      tone: 'green',
    },
    {
      key: 'claimed',
      value: '856',
      icon: 'hands',
      tone: 'blue',
    },
    {
      key: 'waste',
      value: '2.4 ton',
      icon: 'leaf',
      tone: 'amber',
    },
  ],
  incomingRequests: [
    {
      id: 'request-1',
      requester: 'Sarah Wijaya',
      avatarInitials: 'SW',
      itemNameKey: 'request1Item',
      location: 'Mampang Prapatan',
      messageKey: 'request1Message',
      status: 'new',
    },
    {
      id: 'request-2',
      requester: 'Nabila Putri',
      avatarInitials: 'NP',
      itemNameKey: 'request2Item',
      location: 'Pancoran',
      messageKey: 'request2Message',
      status: 'pending',
    },
  ],
  activity: {
    listingsTotal: 4,
    requestTotal: 2,
    statuses: [
      {
        key: 'process',
        value: 2,
        tone: 'blue',
      },
      {
        key: 'completed',
        value: 2,
        tone: 'green',
      },
      {
        key: 'pending',
        value: 1,
        tone: 'amber',
      },
    ],
    latestRequest: {
      itemNameKey: 'request2Item',
      status: 'pending',
    },
  },
  categories: [
    {
      key: 'furniture',
      icon: 'furniture',
      tone: 'amber',
    },
    {
      key: 'electronics',
      icon: 'electronics',
      tone: 'blue',
    },
    {
      key: 'books',
      icon: 'books',
      tone: 'green',
    },
    {
      key: 'baby',
      icon: 'baby',
      tone: 'rose',
    },
    {
      key: 'clothes',
      icon: 'clothes',
      tone: 'slate',
    },
    {
      key: 'home',
      icon: 'home',
      tone: 'sky',
    },
  ],
  listings: [
    {
      id: 'item-1',
      titleKey: 'studyDeskWood',
      categoryKey: 'furniture',
      location: 'Jakarta Selatan',
      timeAgoKey: 'twoHoursAgo',
      conditionKey: 'good',
      availability: 'tersedia',
      requestStatus: null,
      saved: false,
      visual: 'desk',
    },
    {
      id: 'item-2',
      titleKey: 'studyDeskMinimalist',
      categoryKey: 'furniture',
      location: 'Jakarta Selatan',
      timeAgoKey: 'twoHoursAgo',
      conditionKey: 'good',
      availability: 'tersedia',
      requestStatus: null,
      saved: false,
      visual: 'desk',
    },
    {
      id: 'item-3',
      titleKey: 'officeChair',
      categoryKey: 'furniture',
      location: 'Tangerang Kota',
      timeAgoKey: 'threeHoursAgo',
      conditionKey: 'good',
      availability: 'tersedia',
      requestStatus: null,
      saved: true,
      visual: 'chair',
    },
    {
      id: 'item-4',
      titleKey: 'bookshelf',
      categoryKey: 'books',
      location: 'Jakarta Selatan',
      timeAgoKey: 'fiveHoursAgo',
      conditionKey: 'wellMaintained',
      availability: 'proses',
      requestStatus: 'process',
      saved: false,
      visual: 'shelf',
    },
    {
      id: 'item-5',
      titleKey: 'tablewareSet',
      categoryKey: 'home',
      location: 'Depok',
      timeAgoKey: 'sixHoursAgo',
      conditionKey: 'complete',
      availability: 'pending',
      requestStatus: 'pending',
      saved: false,
      visual: 'tableware',
    },
    {
      id: 'item-6',
      titleKey: 'babyBouncer',
      categoryKey: 'baby',
      location: 'Jakarta Selatan',
      timeAgoKey: 'oneDayAgo',
      conditionKey: 'good',
      availability: 'selesai',
      requestStatus: 'completed',
      saved: true,
      visual: 'baby',
    },
  ],
}

export const dashboardModules = dashboardData.communityImpact
